[2024-05-21T15:16:16.695+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T15:16:16.707+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idealista-pipeline.pull_and_save_from_api manual__2024-05-21T15:15:47.516620+00:00 [queued]>
[2024-05-21T15:16:16.712+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idealista-pipeline.pull_and_save_from_api manual__2024-05-21T15:15:47.516620+00:00 [queued]>
[2024-05-21T15:16:16.713+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-21T15:16:16.721+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): pull_and_save_from_api> on 2024-05-21 15:15:47.516620+00:00
[2024-05-21T15:16:16.725+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=451) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T15:16:16.726+0000] {standard_task_runner.py:63} INFO - Started process 452 to run task
[2024-05-21T15:16:16.726+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'idealista-pipeline', 'pull_and_save_from_api', 'manual__2024-05-21T15:15:47.516620+00:00', '--job-id', '298', '--raw', '--subdir', 'DAGS_FOLDER/idealista_dag.py', '--cfg-path', '/tmp/tmp7v055nm7']
[2024-05-21T15:16:16.727+0000] {standard_task_runner.py:91} INFO - Job 298: Subtask pull_and_save_from_api
[2024-05-21T15:16:16.751+0000] {task_command.py:426} INFO - Running <TaskInstance: idealista-pipeline.pull_and_save_from_api manual__2024-05-21T15:15:47.516620+00:00 [running]> on host 05882356329d
[2024-05-21T15:16:16.795+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shv' AIRFLOW_CTX_DAG_ID='idealista-pipeline' AIRFLOW_CTX_TASK_ID='pull_and_save_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T15:15:47.516620+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T15:15:47.516620+00:00'
[2024-05-21T15:16:16.796+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T15:16:17.070+0000] {pull.py:50} INFO - Token acquired successfully.
[2024-05-21T15:16:17.072+0000] {minio.py:45} INFO - Minio successfully connected.
[2024-05-21T15:16:17.079+0000] {minio.py:119} INFO - Start reading data from object name last_pull
[2024-05-21T15:16:17.083+0000] {minio.py:141} INFO - Start writing data to file name last_pull
[2024-05-21T15:16:17.084+0000] {minio.py:173} ERROR - Couldn't save filename to object: last_pull.
Error [Errno 13] Permission denied: '/opt/***/tmp/last_pull'
[2024-05-21T15:16:17.660+0000] {pull.py:108} INFO - Data pulled successfully.
[2024-05-21T15:16:17.662+0000] {minio.py:141} INFO - Start writing data to file name response2024_05_21_p_1.json
[2024-05-21T15:16:17.663+0000] {minio.py:173} ERROR - Couldn't save filename to object: response2024_05_21_p_1.json.
Error [Errno 13] Permission denied: '/opt/***/tmp/response2024_05_21_p_1.json'
[2024-05-21T15:16:20.232+0000] {pull.py:108} INFO - Data pulled successfully.
[2024-05-21T15:16:20.233+0000] {minio.py:141} INFO - Start writing data to file name response2024_05_21_p_2.json
[2024-05-21T15:16:20.263+0000] {minio.py:170} INFO - Successfully save filename to object: response2024_05_21_p_2.json.
[2024-05-21T15:16:22.776+0000] {pull.py:108} INFO - Data pulled successfully.
[2024-05-21T15:16:22.778+0000] {minio.py:141} INFO - Start writing data to file name response2024_05_21_p_3.json
[2024-05-21T15:16:22.806+0000] {minio.py:170} INFO - Successfully save filename to object: response2024_05_21_p_3.json.
[2024-05-21T15:16:24.813+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T15:16:24.814+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T15:16:24.824+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=idealista-pipeline, task_id=pull_and_save_from_api, execution_date=20240521T151547, start_date=20240521T151616, end_date=20240521T151624
[2024-05-21T15:16:24.876+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T15:16:24.889+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-21T15:16:24.891+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
