[2024-05-21T18:43:53.243+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T18:43:53.255+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T16:04:29.980796+00:00 [queued]>
[2024-05-21T18:43:53.261+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T16:04:29.980796+00:00 [queued]>
[2024-05-21T18:43:53.262+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-05-21T18:43:53.269+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_to_kafka> on 2024-05-21 16:04:29.980796+00:00
[2024-05-21T18:43:53.272+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=149) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T18:43:53.273+0000] {standard_task_runner.py:63} INFO - Started process 150 to run task
[2024-05-21T18:43:53.273+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'idealista-pipeline', 'send_to_kafka', 'manual__2024-05-21T16:04:29.980796+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/idealista_dag.py', '--cfg-path', '/tmp/tmpu9r534sg']
[2024-05-21T18:43:53.275+0000] {standard_task_runner.py:91} INFO - Job 321: Subtask send_to_kafka
[2024-05-21T18:43:53.298+0000] {task_command.py:426} INFO - Running <TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T16:04:29.980796+00:00 [running]> on host 0bedcfb13132
[2024-05-21T18:43:53.365+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shv' AIRFLOW_CTX_DAG_ID='idealista-pipeline' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T16:04:29.980796+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T16:04:29.980796+00:00'
[2024-05-21T18:43:53.366+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T18:43:53.375+0000] {minio.py:47} INFO - Minio successfully connected.
[2024-05-21T18:43:53.376+0000] {minio.py:100} INFO - Start reading unprocessed data
[2024-05-21T18:43:53.376+0000] {minio.py:126} INFO - Start reading data from object name processed_files
[2024-05-21T18:43:53.409+0000] {minio.py:113} INFO - Object response2024_05_21_p_1.json was already processed, skipping ...
[2024-05-21T18:43:53.409+0000] {minio.py:113} INFO - Object response2024_05_21_p_2.json was already processed, skipping ...
[2024-05-21T18:43:53.409+0000] {minio.py:126} INFO - Start reading data from object name response2024_05_21_p_3.json
[2024-05-21T18:44:18.508+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-05-21T18:44:18.509+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-21T18:44:18.510+0000] {process_utils.py:132} INFO - Sending 15 to group 150. PIDs of all processes in the group: [150]
[2024-05-21T18:44:18.510+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 150
[2024-05-21T18:44:18.511+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-21T18:44:18.511+0000] {kafka.py:59} WARNING - Error occured while sending data to kafka. Object name response2024_05_21_p_3.json
[2024-05-21T18:44:18.512+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T18:44:18.513+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T18:44:18.517+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=idealista-pipeline, task_id=send_to_kafka, execution_date=20240521T160429, start_date=20240521T184353, end_date=20240521T184418
[2024-05-21T18:44:18.537+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=150, status='terminated', exitcode=0, started='18:43:53') (150) terminated with exit code 0
