[2024-05-21T16:04:47.880+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T16:04:47.891+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T16:04:29.980796+00:00 [queued]>
[2024-05-21T16:04:47.897+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T16:04:29.980796+00:00 [queued]>
[2024-05-21T16:04:47.897+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-21T16:04:47.906+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_to_kafka> on 2024-05-21 16:04:29.980796+00:00
[2024-05-21T16:04:47.909+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1837) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T16:04:47.910+0000] {standard_task_runner.py:63} INFO - Started process 1838 to run task
[2024-05-21T16:04:47.910+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'idealista-pipeline', 'send_to_kafka', 'manual__2024-05-21T16:04:29.980796+00:00', '--job-id', '309', '--raw', '--subdir', 'DAGS_FOLDER/idealista_dag.py', '--cfg-path', '/tmp/tmpf8cvhbz8']
[2024-05-21T16:04:47.911+0000] {standard_task_runner.py:91} INFO - Job 309: Subtask send_to_kafka
[2024-05-21T16:04:47.934+0000] {task_command.py:426} INFO - Running <TaskInstance: idealista-pipeline.send_to_kafka manual__2024-05-21T16:04:29.980796+00:00 [running]> on host 05882356329d
[2024-05-21T16:04:47.979+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shv' AIRFLOW_CTX_DAG_ID='idealista-pipeline' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T16:04:29.980796+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T16:04:29.980796+00:00'
[2024-05-21T16:04:47.980+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T16:04:47.989+0000] {minio.py:47} INFO - Minio successfully connected.
[2024-05-21T16:04:47.990+0000] {minio.py:100} INFO - Start reading unprocessed data
[2024-05-21T16:04:47.990+0000] {minio.py:126} INFO - Start reading data from object name processed_files
[2024-05-21T16:04:48.008+0000] {minio.py:126} INFO - Start reading data from object name response2024_05_21_p_1.json
[2024-05-21T16:04:48.027+0000] {minio.py:126} INFO - Start reading data from object name response2024_05_21_p_2.json
[2024-05-21T16:04:48.047+0000] {minio.py:126} INFO - Start reading data from object name response2024_05_21_p_3.json
[2024-05-21T16:06:18.724+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-05-21T16:06:18.724+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-21T16:06:18.726+0000] {process_utils.py:132} INFO - Sending 15 to group 1838. PIDs of all processes in the group: [1838]
[2024-05-21T16:06:18.726+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1838
[2024-05-21T16:06:18.727+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-21T16:06:18.727+0000] {kafka.py:59} WARNING - Error occured while sending data to kafka. Object name response2024_05_21_p_1.json
[2024-05-21T16:07:18.733+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=1838, name='airflow task ru', status='sleeping', started='16:04:47') did not respond to SIGTERM. Trying SIGKILL
[2024-05-21T16:07:18.734+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 1838
[2024-05-21T16:07:18.741+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1838, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='16:04:47') (1838) terminated with exit code -9
[2024-05-21T16:07:18.742+0000] {standard_task_runner.py:178} ERROR - Job 309 was killed before it finished (likely due to running out of memory)
